name: Create Release
on:
  workflow_call:
    inputs:
      version:
        type: string
        description: "Version"
        required: true
      changelog:
        type: string
        description: "Changelog"
        required: true
jobs:
  create-release:
    name: 🚀 create release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Deprecation Notice
        run: |
          echo "This action is deprecated, please use jcdcdev/jcdcdev.Github.CreateRelease@main instead"
          exit 1