name: Generate Changelog
on:
  workflow_call:
    inputs:
      previous-version:
        type: string
        description: "Previous version - defaults to previous tag if not provided"
        required: false
        default: ''
      target-version:
        type: string
        description: "Version"
        required: true
    outputs:
      changelog: 
        description: "Changelog"
        value: "This action is deprecated, please use jcdcdev/jcdcdev.Github.GenerateChangelog@main instead"
jobs:
  generate-changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest
    env:
      TARGET_VERSION: ${{ inputs.target-version }}
      PREVIOUS_VERSION: ${{ inputs.previous-version }}
    outputs:
      changelog: ""
    steps:
      - name: Deprecation Notice
        run: |
          echo "This action is deprecated, please use jcdcdev/jcdcdev.Github.GenerateChangelog@main instead"
          exit 1