name: 🚀 Release Package
on:
  workflow_call:
    inputs:
        artifact-name:
            type: string
            description: 'Artifact name'
            required: true
        version:
            type: string
            description: 'Version'
            required: true
    secrets:
      nuget-api-key:
        description: 'NuGet API key'
        required: true
jobs:
  nuget:
    name: 🚀 Push to NuGet
    runs-on: ubuntu-latest
    env:
      SEMVER: ${{ inputs.version }}
      ARTIFACT_NAME: ${{ inputs.artifact-name }}
      NUGET_API_KEY: ${{ secrets.nuget-api-key }}
      ARTIFACT_PATH: ./packages
    steps:
      - name: Download package
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_PATH }}
      - name: Push to NuGet
        run: dotnet nuget push ${{ env.ARTIFACT_PATH }}/**/*.nupkg -k ${{ env.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
  create-release:
    name: 🚀 Create release
    needs:
      - nuget
    permissions:
      contents: write
    uses: jcdcdev/jcdcdev.Github.UmbracoSimpleDeploy/.github/workflows/lib/update-release.yml@main
    with:
      version: ${{ inputs.version }}