name: Update Release
on:
  workflow_call:
    inputs:
        version:
            type: string
            description: 'Version'
            required: true
jobs:
  get-versions:
    runs-on: ubuntu-latest
    outputs:
      previous-version: ${{ steps.find-previous-tag.outputs.PREVIOUS_VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Find Previous Version
        id: find-previous-tag
        run: |
          git fetch --tags
          PREVIOUS_TAG=$(git tag --sort=-v:refname | grep -P '^v?[0-9]+\.[0-9]+\.[0-9]+$' | grep -P '^v?[0-9]+\.[0-9]+\.[0-9]+(?=\s+v?[0-9]+\.[0-9]+\.[0-9]+$)' | head -n 1)
          echo "PREVIOUS_VERSION=${PREVIOUS_TAG}" >> $GITHUB_ENV
          echo "PREVIOUS_VERSION=${PREVIOUS_TAG}"
  generate-changelog:
    needs:
      - get-versions
    uses: jcdcdev/jcdcdev.Github.UmbracoSimpleDeploy/.github/workflows/generate-changelog.yml@main
    with:
      target-version: ${{ inputs.version }}
      previous-version: ${{ needs.get-versions.outputs.previous-version }}
  create-release:
    needs:
      - get-versions
      - generate-changelog
    permissions:
      contents: write
    uses: jcdcdev/jcdcdev.Github.UmbracoSimpleDeploy/.github/workflows/create-release.yml@main
    with:
      version: ${{ inputs.version }}
      changelog: ${{ needs.generate-changelog.outputs.changelog }}