name: Update Release
on:
  workflow_call:
    inputs:
        version:
            type: string
            description: 'Version'
            required: true
jobs:
  get-previous-version:
    runs-on: ubuntu-latest
    outputs:
      previous-version: ${{ steps.find-previous-tag.outputs.previous-version }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Find Previous Version
      id: find-previous-tag
      run: |
        git fetch --tags
        PREVIOUS_TAG=$(git tag --sort=-v:refname | grep -P '^v?\d+\.\d+\.\d+$' | grep -B 1 ${{ inputs.version }} | head -n 1)
        echo "previous-version=${PREVIOUS_TAG}" >> $GITHUB_OUTPUT
        echo "previous-version=${PREVIOUS_TAG}"

        if [ -z "$PREVIOUS_TAG" ]; then
          echo "No previous version found"
          exit 1
        fi
  generate-changelog:
    needs:
      - get-previous-version
    uses: jcdcdev/jcdcdev.Github.UmbracoSimpleDeploy/.github/workflows/generate-changelog.yml@main
    with:
      target-version: ${{ inputs.version }}
      previous-version: ${{ needs.get-previous-version.outputs.previous-version }}
  create-release:
    needs:
      - get-previous-version
      - generate-changelog
    permissions:
      contents: write
    uses: jcdcdev/jcdcdev.Github.UmbracoSimpleDeploy/.github/workflows/create-release.yml@main
    with:
      version: ${{ inputs.version }}
      changelog: ${{ needs.generate-changelog.outputs.changelog }}