name: Update all releases
on:
    workflow_call:
        inputs:
            start-version:
                description: 'The version to start from'
                required: true
                default: '0.1.0'
                type: string
            end-version:
                description: 'The version to end at'
                required: false
                default: '999.999.999'
                type: string
jobs:
  get-tags:
    runs-on: ubuntu-latest
    outputs:
        versions: ${{ steps.set-matrix.outputs.versions }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get all tags
        shell: pwsh
        env:
            START_VERSION: ${{ inputs.start-version }}
            END_VERSION: ${{ inputs.end-version }}
        id: set-matrix
        run: |
            git fetch --tags
            $allTags = git tag | Sort-Object -Ascending
            $tags = @()
            foreach ($tag in $allTags) {
                echo "Checking tag $tag"
                if ($tag -ge $env:START_VERSION -and $tag -le $env:END_VERSION) {
                    $tags += $tag
                }
            }

            $versions = ConvertTo-Json -InputObject $tags -Compress
            echo "versions=$versions" >> $env:GITHUB_OUTPUT
            echo "Versions are`n$versions"
  update-release:
    needs: 
        - get-tags
    strategy:
        fail-fast: false
        max-parallel: 1
        matrix:
            version: ${{fromJson(needs.get-tags.outputs.versions)}}
    uses: jcdcdev/jcdcdev.Github.UmbracoSimpleDeploy/.github/workflows/update-release.yml@main
    permissions:
        contents: write
    with:
        version: ${{ matrix.version }}