name: Update Release
on:
  workflow_call:
    inputs:
      version:
        type: string
        description: 'Version'
        required: true
jobs:
  update-release:
    runs-on: ubuntu-latest
    steps:
    - name: Deprecation Notice
      run: |
        echo "This action is deprecated, please use jcdcdev/jcdcdev.Github.CreateRelease@main instead"
        exit 1